### ISSUE TITLE
Could you please help to detect groups

### ISSUE THREAD

**Issue by jiwanjatra** [ACSoupir/Bioinformatics_RNASeq#1]
> detectGroups <- function (x){  # x are col names
  tem <- gsub("[0-9]*$","",x) # Remove all numbers from end
  #tem = gsub("_Rep|_rep|_REP","",tem)
  tem <- gsub("_$","",tem); # remove "_" from end
  tem <- gsub("_Rep$","",tem); # remove "_Rep" from end
  tem <- gsub("_rep$","",tem); # remove "_rep" from end
  tem <- gsub("_REP$","",tem)  # remove "_REP" from end
  return( tem )
}

I have trouble understanding this step for my data analysis. My sample names are as such:
1. R1_AB_1, R2_AB_2 and R3_AB_3
2. R1_CD_1, R2_CD_2 and R3_CD_3

I need to group AB as one group and CD as another. 1,2,3 are three replicates for each treatment. R is just a representation [ A placeholder ], to better categorize the data

**Comment by ACSoupir** [comment]
I don't understand the question?

With a little editing to the function:

```
detectGroups <- function (x){ # x are col names
    tem <- gsub("^[^_]*_([^_]*).*","\\1",x)
    return( tem )
}
```

you can pass in your column names and it should return something like:
`[1] "AB" "AB" "AB" "CD" "CD" "CD"`

Is this what you are referring to? The naming of your samples just requires a change to the function.

Found this in a quick Google.
https://stackoverflow.com/questions/50945040/remove-characters-before-first-and-after-second-underscore-extracting-string-bet

Hope this helps.
ACS

**Comment by jiwanjatra** [comment]
> I don't understand the question?
> 
> With a little editing to the function:
> 
> ```
> detectGroups <- function (x){ # x are col names
>     tem <- gsub("^[^_]*_([^_]*).*","\\1",x)
>     return( tem )
> }
> ```
> 
> you can pass in your column names and it should return something like:
> `[1] "AB" "AB" "AB" "CD" "CD" "CD"`
> 
> Is this what you are referring to? The naming of your samples just requires a change to the function.
> 
> Found this in a quick Google.
> https://stackoverflow.com/questions/50945040/remove-characters-before-first-and-after-second-underscore-extracting-string-bet
> 
> Hope this helps.
> ACS

Thank you for reaching out this quick. From my understanding, we are defining  'detectGroup' so that we can group similar groups together ( Treatment_A  versus Treatment_B for me). I want to confirm if these are actually grouped together. This was part of the problem because once I drew PCA plots ( _both a simple PCA and prettier PCA plot_ ) from your code, for the prettier plot I dont see them group togther

Here is my sample and treatment group : 
<img width="271" alt="image" src="https://user-images.githubusercontent.com/79867548/109713423-2fe42800-7b6f-11eb-8176-f42c855f76d0.png">

Here is pca plot drawn with code:  _plotPCA(rld, intgroup = "tissue_type"_
<img width="635" alt="image" src="https://user-images.githubusercontent.com/79867548/109713549-599d4f00-7b6f-11eb-9c0e-cbbcc1a3767f.png">

Here is the prettier pca plot : 
<img width="664" alt="image" src="https://user-images.githubusercontent.com/79867548/109713597-6de14c00-7b6f-11eb-8a62-5880af3f54ad.png">

For the second figure it seems like each individual replicate of the treatment are grouped individually.

I wanted to make sure I am following your analysis properly since our defined 'detectGroup' is used for heat maps and downstream

**Comment by ACSoupir** [comment]
Got ya. Yeah good deal. 

It looks like using the new detect groups function you should be able to pull the `AB` and `CD` alone out when `cbind` ing the PCA data frame. Let me know if the new function works (can simply test `detectGroups(colnames(assay(rld)))` in the console at the bottom of R studio after assigning the function). 

The initial detect groups is meant to be as simple and applicable as possible - many label their samples different so it isn't going to work for everyone without possibly slight modifications. If you always have your names similar, a one liner like above is sufficient which is really nice.

ACS
